name: CNAME & Repo Config Checker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checking "test3" exists in test.txt
        run: grep "test3" -q test.txt && echo "CORRECT" || sed -i '3s/.*/broken/' test.txt
      - name: If "test5" does not exist in test.txt, replaces line 3
        run: grep "test5" -q test.txt && echo "SOMETHING BROKE" || sed -i '3s/.*/  it works! and this is line 3/' test.txt
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: If changes have been made, commit and push
        run: if git diff-index --quiet HEAD --; then echo "No changes"; else git add -A && git commit -m "Changed line 3" && git push; fi
