name: CNAME & Repo Config Checker3

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install deps
        run: sudo snap install remarshal && sudo snap install jq && sudo snap install yq
      - name: Check & fix repo if necessary
        run: |
          repoExpectedVal="hyraxbio-cms/hyraxbio.com-v2"
          config=$(yaml2json static/admin/config.yml) && echo "$config"
          repo=$(echo "$config" | jq -r '.backend.repo') && echo "$repo"
          if ! [ "$repo" == "$repoExpectedVal" ]; then newjson=$(echo "$config" | jq --arg repo "$repoExpectedVal" \ '.backend.repo=$repo') && echo $newjson > static/admin/config.yml && echo "static/admin/config.yml as json:" && cat static/admin/config.yml && cat static/admin/config.yml | yq -P && cat static/admin/config.yml | yq -P |& tee static/admin/config.yml && echo "> modified static/admin/config.yml file:" && cat static/admin/config.yml; fi
      - name: Check & fix CNAME if necessary
        run: |
          cnameExpectedVal="hyraxbio.com"
          cname=$(cat static/CNAME)
          if ! [ "$cname" == "$cnameExpectedVal" ]; then echo "$cnameExpectedVal" > static/CNAME && echo "> modified CNAME file:" && cat static/CNAME; fi
      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: If changes have been made, commit and push
        run: if [ -n "$(git status --porcelain)" ]; then git add -A && git commit -m "Fixed CNAME/repo3" && git push; else echo "No changes"; fi
