name: staging-auto-updater

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          repository: hyrax-stanley/test-actions
          path: test-actions
      - name: ls
        run: ls
      - name: Enter directory
        run: cd test-actions
      - name: Output git status
        run: status=$(git status) && echo "$status"
      - name: Output remote origin URL
        run:  origin=$(git remote show origin) && echo "$origin"
      - name: Push changes to staging repo
        run: |
          git config --global url."https://${{ secrets.ACESS_TOKEN }}@github".insteadOf https://github
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git clone git@github.com:hyrax-stanley/test-actions.git
          cd test-actions
          git pull git@github.com:hyraxbio-cms/test-actions.git main --allow-unrelated-histories
          if [ -n "$(git status --porcelain)" ]; then git add -A && git commit -m "Updated from live" && git push; else echo "No changes"; fi
        
