name: staging-auto-updater

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          repository: hyrax-stanley/test-actions
          path: test-actions
      - name: Pull live changes and push to staging
        run: |
          cd test-actions
          git config user.name "Jacques Louw"
          git config user.email "<jacques@hyraxbio.com>"
          git pull https://github.com/hyraxbio-cms/test-actions.git main --allow-unrelated-histories
          if [ -n "$(git status --porcelain)" ]; then git add -A && git commit -m "Updated from live" && git push; else echo "No changes"; fi
        
